# Generated by Django 2.2.6 on 2019-10-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
